apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: mlflow
  name: mlflow-postgres-pvc
  labels:
    type: local
    app: mlflow-database
spec:
  storageClassName: ebs-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi