# Envs
airflow_database_user        = "zezinho123"
airflow_database_password    = "zezinho123"
airflow_fernet_key           = "yWBoJq-wNr3EPDUJDyYzechgK3Ox4uydv-BFPakTcYE="
airflow_dags_repo_url        = ""
airflow_github_username      = ""
airflow_github_token_classic = ""
mlflow_artifact_bucket       = ""
mlflow_s3_access_key_id      = ""
mlflow_s3_secret_access_key  = ""