apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: airflow
  name: airflow-postgres-pvc
  labels:
    app: airflow-database
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi