apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ${AIRFLOW_NAMESPACE}
  name: airflow-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-database
  template:
    metadata:
      labels: 
        app: airflow-database
    spec:
      volumes:
      - name: airflow-pv-data
        persistentVolumeClaim:
          claimName: airflow-postgres-pvc
      containers:
        - name: postgres
          image: 'postgres:16'
          imagePullPolicy: IfNotPresent
          env:
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
          - name: POSTGRES_USER
            value: ${AIRFLOW_DATABASE_USER}
          - name: POSTGRES_PASSWORD
            value: ${AIRFLOW_DATABASE_PASSWORD}
          - name: POSTGRES_DB
            value: ${AIRFLOW_DATABASE_NAME}
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: airflow-pv-data