apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: airflow
  name: airflow-postgres-pvc
  labels:
    type: local
    app: airflow-database
spec:
  storageClassName: ebs-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi