apiVersion: v1
kind: Service
metadata:
  namespace: airflow
  name: airflow-database-svc
  labels:
    app: airflow-database
spec:
  type: ClusterIP
  ports:
    - port: 5432
  selector:
    app: airflow-database